export const ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
  },
  USERS: {
    LIST: "/users",
    CREATE: "/users",
    BY_ID: (id: string) => `/users/${id}`,
    UPDATE_STATUS: (id: string) => `/users/${id}/status`,
    DELETE: (id: string) => `/users/${id}`,
  },
  MEMBERS: {
    LIST: "/members",
    CREATE: "/members",
    BY_ID: (id: string) => `/members/${id}`,
    BY_STUDENT_ID: (studentId: string) => `/members/student/${studentId}`,
    UPDATE: (id: string) => `/members/${id}`,
    DELETE: (id: string) => `/members/${id}`,
  },
  CARDS: {
    CREATE: "/cards",
    BY_UID: (cardUid: string) => `/cards/${cardUid}`,
    BY_MEMBER: (memberId: string) => `/members-cards/${memberId}`,
    UPDATE: (cardUid: string) => `/cards/${cardUid}`,
    TOGGLE: (cardUid: string) => `/cards/${cardUid}/toggle`,
    DELETE: (cardUid: string) => `/cards/${cardUid}`,
    AVAILABLE_CASUAL: "/cards/casual-available",
  },
  PAYMENT: {
    DEPOSIT: (cardUid: string) => `/cards/${cardUid}/deposit`,
    WITHDRAW: (cardUid: string) => `/cards/${cardUid}/withdraw`,
    BALANCE: (cardUid: string) => `/cards/${cardUid}/balance`,
    TRANSACTIONS: (cardUid: string) => `/cards/${cardUid}/transactions`,
  },
  SESSIONS: {
    CHECK_IN: "/sessions/checkin",
    CHECK_OUT: (id: string | number) => `/sessions/${id}/checkout`,
    BY_CARD: (cardUid: string) => `/sessions/card/${cardUid}`,
    BY_PLATE: (plate: string) => `/sessions/plate/${encodeURIComponent(plate)}`,
    BY_ID: (id: string | number) => `/sessions/${id}`,
  },
  CARD_REQUESTS: {
    CREATE: "/card-requests",
    MINE: "/card-requests/me",
    LIST: "/card-requests",
    APPROVE: (id: string) => `/card-requests/${id}/approve`,
    REJECT: (id: string) => `/card-requests/${id}/reject`,
    BLOCK: (id: string) => `/card-requests/${id}/block`,
  },
  PARKING_LOTS: {
    LIST: "/parking-lots",
    BY_ID: (id: string) => `/parking-lots/${id}`,
    CREATE: "/parking-lots",
    UPDATE: (id: string) => `/parking-lots/${id}`,
    DELETE: (id: string) => `/parking-lots/${id}`,
  },
  SHIFTS: {
    LIST: "/shifts",
    CREATE: "/shifts",
    BY_ID: (id: string) => `/shifts/${id}`,
    UPDATE_STATUS: (id: string) => `/shifts/${id}/status`,
    UPDATE_NOTES: (id: string) => `/shifts/${id}/notes`,
    DELETE: (id: string) => `/shifts/${id}`,
    ASSIGN: (id: string) => `/shifts/${id}/assign`,
    UNASSIGN: (id: string) => `/shifts/${id}/unassign`,
  },
  INCIDENTS: {
    LIST: "/incidents",
    REPORT: "/incidents",
    RESOLVE: (id: string) => `/incidents/${id}/resolve`,
    ESCALATE: (id: string) => `/incidents/${id}/escalate`,
  },
  DEVICES: {
    LIST: "/devices",
    BY_ID: (id: string) => `/devices/${id}`,
    CREATE: "/devices",
    UPDATE_STATUS: (id: string) => `/devices/${id}/status`,
    UPDATE_NOTES: (id: string) => `/devices/${id}/notes`,
    ALERTS: "/devices/alerts",
    FAULT: (id: string) => `/devices/${id}/fault`,
    RESOLVE_ALERT: (alertId: string) => `/devices/alerts/${alertId}/resolve`,
  },
  NOTIFICATIONS: {
    LIST: "/notifications",
    CREATE: "/notifications",
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    MARK_ALL_READ: "/notifications/read-all",
  },
  SUPPORT: {
    CREATE: "/support/tickets",
    MINE: "/support/tickets/me",
    BY_ID: (id: string) => `/support/tickets/${id}`,
    RESPONSES: (id: string) => `/support/tickets/${id}/responses`,
    LIST: "/support/tickets",
    UPDATE_STATUS: (id: string) => `/support/tickets/${id}/status`,
  },
  VISITOR: {
    CREATE: "/visitor/passes",
    MINE: "/visitor/passes/me",
    BY_ID: (id: string) => `/visitor/passes/${id}`,
    CANCEL: (id: string) => `/visitor/passes/${id}/cancel`,
  },
  VEHICLES: {
    CREATE: "/vehicles",
    MINE: "/vehicles/me",
    LIST: "/vehicles",
    BY_PLATE: (plate: string) => `/vehicles/plate/${plate}`,
    DELETE: (id: string) => `/vehicles/${id}`,
  },
  MONTHLY_PASS: {
    LIST: "/monthly-passes",
    CREATE: "/monthly-passes",
    TOGGLE_AUTO_RENEW: (id: string) => `/monthly-passes/${id}/toggle-auto-renew`,
  },
} as const;
